name: CI

on:
  pull_request:
    branches:
      - 'main'

  push:
    branches:
      - 'main'
env:
# Your ruby version
  RUBY: '2.6.3'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          ruby-version: ${{ env.RUBY }}
      - name: Run linters
        run: |
          bundle exec rubocop app config --parallel
          bundle exec reek app config
          bundle exec rails_best_practices .
          bundle exec brakeman app -z -q --force
  test:
   name: Spect Test
   runs-on: ubuntu-latest
   services:
     mysql:
       image: mysql:5.7
       env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: rails_app_test
       ports:
        - 3306:3306
   steps:
     - uses: actions/checkout@v2
     - name: Setup environment
       uses: ./.github/actions/setup
       with:
         ruby-version: ${{ env.RUBY }}
     - name: Get yarn cache
       id: yarn-cache
       run: echo "::set-output name=dir::$(yarn cache dir)"
     - name: Cache yarn
       uses: actions/cache@v2
       with:
         path: ${{ steps.yarn-cache.outputs.dir }}
         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
         restore-keys: |
           ${{ runner.os }}-yarn-
     - name: Install dependencies
       run: |
         yarn install --frozen-lockfile
     - name: Run tests
       env:
         RAILS_ENV: test
         DATABASE_HOST: 127.0.0.1
       run: |
         bin/rails db:create db:migrate
         bundle exec rspec