name: deploy to ec2

on:
  pull_request:
    branches:
      - 'development'

env:
  APP_NAME: 'rails-project'

jobs:
#First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build the docker_compose
      run: docker-compose up -d --build

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy in EC2
        uses: actions/checkout@v2 

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SECRET_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.AWS_HOST }}
          REMOTE_USER: ${{ secrets.AWS_USER }}
          SCRIPT_AFTER: |
            whoami
              cd /${{ env.APP_NAME }} &&
              git checkout dev &&
              git fetch --all &&
              git reset --hard origin/master &&
              git pull origin dev &&
              docker-compose -f docker-compose.yml up -d --build
