name: deploy to ec2

on:
  pull_request:
    branches:
      - 'development'

env:
  APP_NAME: 'rails-project'

jobs:
#First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build the docker_compose
      run: docker-compose up -d --build

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy in EC2
        uses: actions/checkout@v2 
      
        env:
            AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY  }}
            HOSTNAME : ${{ secrets.AWS_HOST  }}
            USER_NAME : ${{ secrets.AWS_USER  }}
      - name: create ssh folder
        run: mkdir /home/runner/.ssh/

      - name: create private key
        run: touch /home/runner/.ssh/private_key.pem

      - name: copy private key
        run: 'echo "$AWS_SECRET_KEY" > /home/runner/.ssh/private_key.pem'

      - name: change permission to private key
        run: chmod 400 /home/runner/.ssh/private_key.pem
    

      - name: SSH connect
        run: |
          ssh -i /home/runner/.ssh/private_key.pem deploy@13.114.122.61
          #Now we have got the access of EC2 and we will start the deploy .
          #cd /${{ env.APP_NAME }} &&
          #git checkout dev &&
          #git fetch --all &&
          #git reset --hard origin/master &&
          #git pull origin dev &&
          #docker-compose -f docker-compose.yml up -d --build 