name: Push rails app to docker hub
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  push_rails_app_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push rails app
        uses: docker/build-push-action@v4
        with:
          context: ./docker/app
          file: ./docker/app/Dockerfile
          push: true
          tags: 19081998125/rails-app:v1
      - name: Build and push NGINX 
        uses: docker/build-push-action@v4
        with:
          context: ./docker/nginx
          file: ./docker/nginx/Dockerfile
          push: true
          tags: 19081998125/nginx:v1
